### PR TITLE
callGetFulfillmentPreviewResult + callCreateFulfillmentOrder

### PR DESCRIPTION
**Pull request by maykino**

### CODE REVIEW

**Comment by caponica** [comment]
Hi @maykino , could you provide some explanation of what this is fixing and the changes you have made?

**Comment by caponica** [comment]
OK, I just pushed an update which should cover the first half (four commits) of this PR - it has added the order status constants and a way to filter by OrderStatus. The ReportType filter was already in the latest version of MwsFeedAndReportClientPack

I'll review the OutboundClientPack as soon as I can and then either pull them or create a new commit based on your work.

**Comment by maykino** [comment]
Thank you. It wasn't a fix. I just added a wrapper around the FBAOutbound
api. Let me know if you have any questions.

**Comment by caponica** [comment]
A basic FbaOutboundClientPack has been added in the latest version of the code, which implements the three API methods which were referenced in this PR.

**Pull request closed without merging**
