### PR TITLE
Bunch of improvements that I've added in the past 2 years

### PR DESCRIPTION
**Pull request by maykino**

### CODE REVIEW

**Comment by jasonhebert** [comment]
Modifying the files in the `src/AmazonPhpClientLibrary` directory, imho, shouldn't be done. These are library files provided by Amazon and in the event that these files are updated and incorporated here these changes will be overwritten.

**Comment by caponica** [comment]
Hi @maykino - I had a very quick look and there may be some gems in here, but you need to rebase your work to the current master before I can review and accept it.

**Comment by maykino** [comment]
Sure and sorry about the mess. I've been using it for my own purposes but
at some point decided to help others. I will get to it when I have a
moment.

**Comment by caponica** [comment]
I'm going to have to close this because it's too far behind master.

If you can rebase it then you're welcome to resubmit.

**Pull request closed without merging**
